apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - angelnu-charts.yaml
  - appscode.yaml
  - authentik.yaml
  - bitnami.yaml
  - ceph-csi.yaml
  - forecastle.yaml
  - gitea.yaml
  - hajimari.yaml
  - infracloudio-charts.yaml
  - ingress-nginx.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-dashboard.yaml
  - nextcloud.yaml
  - node-feature-discovery-charts.yaml
  - raspberrymatic.yaml
  - rook-ceph.yaml
  - searxng.yaml
  - weaveworks-kured-charts.yaml
  - wobcom.yaml
  - zalando-postgres-operator.yaml
  - zalando-postgres-ui.yaml
