# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: mapping
# spec:
#   nodeSelector:
#     node-role.kubernetes.io/worker: ''
#   desiredState:
#     ovn:
#       bridge-mappings:
#       - localnet: localnet1
#         bridge: br-ex
#         state: present