apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: angelnu-helm-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://angelnu.github.io/helm-charts
  timeout: 15m