apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: global-settings
data:
  CLUSTER_MAIL_SERVER: mail.kube-system
  CLUSTER_MAIL_SERVER_PORT: "25"
  # mcvlan_static_range: &anchor_ip_mcvlan_static_range
  # 192.168.1.0-192.168.1.63
  CLUSTER_MACVLAN_HA: "1"
  #CLUSTER_MACVLAN_PLEX: "2"
  #CLUSTER_MACVLAN_CCU: "3"
  CLUSTER_MACVLAN_UNIFI: "4"

  # lb_static_range: &anchor_ip_lb_static_range
  # 192.168.1.128-192.168.1.192
  CLUSTER_LB_INGRESS: "128"
  CLUSTER_LB_GOW: "129"
  CLUSTER_LB_HA: "130"
  CLUSTER_LB_CCU: "131"
  CLUSTER_LB_GITEA: "132"
  CLUSTER_LB_PLEX: "133"
  #CLUSTER_LB_OPENVPN: "134"
  CLUSTER_LB_LORAFWD: "135"
  CLUSTER_LB_MOSQUITTO: "136"
  #CLUSTER_LB_UNIFI: "137"
  CLUSTER_LB_MAIL: "138"
  CLUSTER_LB_JELLYFIN: "140"
  CLUSTER_LB_MADDY: "141"

  NETWORK_K8S_CLUSTER_CIDR: "10.0.0.0/8"

  CEPH_MONITOR_HOST_1: 192.168.4.11:6789
  CEPH_MONITOR_HOST_2: 192.168.4.12:6789
  CEPH_MONITOR_HOST_3: 192.168.4.13:6789