apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: settings
  namespace: flux-system
spec:
  interval: 10m5s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./settings/production
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg