apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: Merge
  name: default
spec:
  defaultCertificate:
    name: "${CLUSTER_DOMAIN_CERT}"
  routeAdmission:
    wildcardPolicy: WildcardsAllowed
