apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - angelnu-charts.yaml
  - bitnami.yaml
  - gitea.yaml
  - ingress-nginx.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - podinfo.yaml
  - zalando-postgres-operator.yaml
  - zalando-postgres-ui.yaml
