---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # Cluster dependent
  CLUSTER_NAME: prod

  CLUSTER_EXTERNAL_SUBNET_PREFIX: "192.168.5"
  CLUSTER_LB_RANGE: "192.168.5.128-192.168.5.192"

  FLUX_NOTIFICATIONS_CHANNEL: k8s
  BOTKUBE_NOTIFICATIONS_CHANNEL: k8s

  NFS_KUBERNETES: /volume1/kubernetes
  NFS_DOWNLOADS: /volume1/downloads
  NFS_SOFTWARE: /volume1/software
  NFS_VIDEO: /volume1/video
  NFS_MUSIC: /volume1/music
