---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - networkPolicy.yaml
  - qbittorrent/ks.yaml
  - readarr/ks.yaml
  - sonarr/ks.yaml
  - terminal/ks.yaml
  - ubuntu/ks.yaml
