apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - apache-musicindex
  - comics
  - deepstack
  - esphome
  - gatus
  - gitea
  #- gow
  - hajimari
  - handbrake
  - home-assistant
  - homer
  - jellyfin
  - lorawan
  - mealie
  - music-manager
  - nextcloud
  - novnc
  - paperless
  # - plex
  - photoprism
  - searxng
  # - raspberrymatic
  - recipes
  - reverse-proxy
  - tt-rss
  - unifi
