collections:
  - name: community.general
    version: 11.4.2
  - name: community.sops
    version: 2.2.7
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.6.2