apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - esphome
  - gitea
  - heimdall
  - home-assistant
  - homer
  - lorawan
  - nextcloud
  - musicIndex.yaml
  - nfs
  - paperless
  - plex
  - photoprism
  - raspberrymatic
  - recipes
  - reverse-proxy
  - statping
  - tt-rss
  - unifi
