---
name: Schedule - Renovate
permissions:
  contents: write # To create branches and commits for updates
  pull-requests: write # To create, update, and close Pull Requests
  issues: write # To create the Dependency Dashboard issue
  checks: read # To see if CI passed before automerging (if enabled)
  statuses: read # To check commit statuses

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"
      - ".github/renovate/**.json5"
      - ".github/workflows/schedule-renovate.yaml"

jobs:
  renovate:
    name: Renovate
    uses: angelnu/github-workflows/.github/workflows/run-renovate.yaml@main
    with:
      configurationFile: ".github/renovate.json5"
      dryRun: ${{ inputs.dryRun || 'false' }}
      renovateLogLevel: ${{ inputs.logLevel || 'debug' }}
    secrets:
      app_id: ${{ secrets.ANGELNU_APP_ID }}
      app_private_key: ${{ secrets.ANGELNU_APP_PRIVATE_KEY }}
